using InkscapeTileMaker.Models;
using InkscapeTileMaker.Services;
using SkiaSharp;

namespace InkscapeTileMaker.Utility
{
	public partial class TilemapPackager
	{
		private readonly ITilesetConnection _tileSetConnection;
		private readonly ITilesetRenderingService _renderingService;

		public TilemapPackager(ITilesetConnection tileSetConnection, ITilesetRenderingService renderingService)
		{
			_tileSetConnection = tileSetConnection;
			_renderingService = renderingService;
			if (tileSetConnection.Tileset == null) throw new ArgumentException("Tileset connection must have a tileset.", nameof(tileSetConnection));
		}

		/// <summary>
		/// Renders a tilemap into a png, where each tile corresponds to a single position in the tilemap. 
		/// The tile's image is generated by compositing all the tiles that overlap that position in the tilemap, applying their transformations as necessary.
		/// </summary>
		public async Task ExportTilemap(
			ITilemap tilemap,
			Scale tilePixelSize,
			Stream outputStream,
			CancellationToken cancellationToken = default)
		{
			var imageSize = new Scale(
				tilemap.TileGridRect.Width * tilePixelSize.Width,
				tilemap.TileGridRect.Height * tilePixelSize.Height);

			using var bmp = new SKBitmap(imageSize.Width, imageSize.Height);
			using var canvas = new SKCanvas(bmp);

			foreach (var (tiles, (x, y)) in tilemap)
			{
				if (tiles.Count == 0) continue;
				SKRect tileRect = GetTileRect(y, x, tilePixelSize);
				tileRect.Offset(0.5f, 0.5f);
				foreach (var tileData in tiles)
				{
					await RenderTile(canvas, tileData, tileRect, tilePixelSize, cancellationToken);
				}
			}

			using var image = SKImage.FromBitmap(bmp);
			using var data = image.Encode(SKEncodedImageFormat.Png, 100);
			using var pngStream = data.AsStream();

			await pngStream.CopyToAsync(outputStream, cancellationToken);
		}

		private async Task RenderTile(SKCanvas canvas, TileData tileData, SKRect rect, Scale tilePixelSize, CancellationToken cancellationToken)
		{
			using var tileBitmap = new SKBitmap(tilePixelSize.Width, tilePixelSize.Height);

			int width = _tileSetConnection.Tileset!.TilePixelSize.Width;
			int height = _tileSetConnection.Tileset!.TilePixelSize.Height;
			int top = height * tileData.tile.Row;
			int left = width * tileData.tile.Column;
			int right = left + width;
			int bottom = top + height;

			using (var pngStream = await _renderingService.RenderSegmentAsync(_tileSetConnection.CurrentFile!, "png", left, top, right, bottom, tilePixelSize, cancellationToken))
			{
				using var bitmap = SKBitmap.Decode(pngStream);
				bitmap.CopyTo(tileBitmap);
			}

			using var transformedBitmap = new SKBitmap(tilePixelSize.Width, tilePixelSize.Height);
			using (var tileCanvas = new SKCanvas(transformedBitmap))
			{
				tileCanvas.Clear(SKColors.Transparent);

				float cx = tilePixelSize.Width / 2f;
				float cy = tilePixelSize.Height / 2f;

				var matrix = SKMatrix.Identity;
				matrix = matrix.PostConcat(SKMatrix.CreateTranslation(-cx, -cy));
				matrix = matrix.PostConcat(tileData.transformation.ToSKMatrix());
				matrix = matrix.PostConcat(SKMatrix.CreateTranslation(cx, cy));

				tileCanvas.SetMatrix(matrix);
				tileCanvas.DrawBitmap(tileBitmap, 0, 0);
			}
			canvas.DrawBitmap(transformedBitmap, rect);
		}

		private SKRect GetTileRect(int row, int column, Scale tilePixelSize)
		{
			float width = tilePixelSize.Width;
			float height = tilePixelSize.Height;
			float top = height * row;
			float left = width * column;
			float right = left + width;
			float bottom = top + height;
			return new SKRect(left, top, right, bottom);
		}
	}
}
